#!/bin/zsh

DAY=day-$1

cp -r ./template/. ./$DAY
cd ./$DAY
mv ./haskell.hs ./$DAY.hs
mv ./rust.rs ./$DAY.rs
mv ./python.py ./$DAY.py

echo "[package]
name = '$DAY'
version = '1.0.0'

[[bin]]
name = '$DAY'
path = './$DAY.rs'" >> Cargo.toml
